# Generated by Django 5.2.15 on 2026-08-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RecetaCinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_por_unidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cinta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='inventario.iteminventario')),
                ('producto_terminado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_cinta', to='inventario.iteminventario')),
            ],
        ),
    ]
