# Generated by Django 5.2.15 on 2026-08-22 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_iteminventario_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
