# Generated by Django 5.2.15 on 2026-08-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_listas',
            field=models.PositiveIntegerField(default=0, help_text='Unidades ya armadas y listas para entrega inmediata. Solo informativo, no bloquea la venta.'),
        ),
    ]
