# Generated by Django 5.2.15 on 2026-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_unidades_listas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('FLORES', 'Flores'), ('CAJAS_SORPRESA', 'Cajas sorpresa'), ('LLAVEROS', 'Llaveros'), ('MONAS', 'Moñas'), ('DETALLES_HOMBRES', 'Detalles hombres'), ('BOMBAS_CHOCOLATE', 'Bombas de chocolate')], max_length=30, unique=True),
        ),
    ]
