# Generated by Django 5.2.15 on 2026-08-16 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto destacado'), ('BANNER', 'Banner promocional')], default='BANNER', max_length=10)),
                ('imagen', models.ImageField(blank=True, help_text="Solo si el tipo es 'Banner promocional'. Si es Producto, se usa la imagen del producto.", null=True, upload_to='catalogo/carrusel/')),
                ('titulo', models.CharField(blank=True, help_text="Solo para banners. Ej: 'Mes del amor y la amistad'", max_length=100)),
                ('subtitulo', models.CharField(blank=True, help_text="Solo para banners. Ej: 'El mes perfecto para hacer tu pedido'", max_length=200)),
                ('texto_boton', models.CharField(blank=True, default='Ver más', max_length=40)),
                ('url_destino', models.CharField(blank=True, help_text='A dónde lleva el botón, ej: /catalogo/lista/. Vacío = sin botón.', max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo para ocultarlo sin borrarlo.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, help_text="Solo si el tipo es 'Producto destacado'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrusel', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Item del carrusel',
                'verbose_name_plural': 'Items del carrusel',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
