# Generated by Django 5.2.15 on 2026-08-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_itemcarrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrusel',
            name='ajuste_imagen',
            field=models.CharField(choices=[('CONTENER', 'Mostrar imagen completa (con fondo difuminado)'), ('CUBRIR', 'Rellenar el banner (recorta los bordes)')], default='CONTENER', help_text='Cómo se muestra la imagen dentro del banner.', max_length=10),
        ),
        migrations.AddField(
            model_name='itemcarrusel',
            name='foco_x',
            field=models.PositiveSmallIntegerField(default=50, help_text="Solo si el ajuste es 'Rellenar'. Punto horizontal (0-100) que siempre debe verse."),
        ),
        migrations.AddField(
            model_name='itemcarrusel',
            name='foco_y',
            field=models.PositiveSmallIntegerField(default=50, help_text="Solo si el ajuste es 'Rellenar'. Punto vertical (0-100) que siempre debe verse."),
        ),
    ]
