# Generated by Django 5.2.15 on 2026-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_itemcarrusel_ajuste_imagen_itemcarrusel_foco_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrusel',
            name='foco_x',
        ),
        migrations.RemoveField(
            model_name='itemcarrusel',
            name='foco_y',
        ),
        migrations.AlterField(
            model_name='itemcarrusel',
            name='ajuste_imagen',
            field=models.CharField(choices=[('CONTENER', 'Mostrar imagen completa (con fondo difuminado)'), ('RECORTAR', 'Recortar imagen a la medida del banner')], default='CONTENER', help_text='Cómo se muestra la imagen dentro del banner.', max_length=10),
        ),
    ]
