# Generated by Django 5.2.15 on 2026-08-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_itemcarrusel_foco_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDelMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto del catálogo'), ('PERSONALIZADO', 'Contenido personalizado')], default='PRODUCTO', max_length=15)),
                ('imagen', models.ImageField(blank=True, help_text="Solo si el tipo es 'Contenido personalizado'. Si es Producto, se usa la imagen del producto.", null=True, upload_to='catalogo/destacados_mes/')),
                ('titulo', models.CharField(blank=True, help_text='Se usa el nombre del producto si está vacío.', max_length=100)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción corta para la card.', max_length=200)),
                ('texto_boton', models.CharField(blank=True, default='Ver producto', max_length=40)),
                ('url_destino', models.CharField(blank=True, help_text='A dónde lleva el botón. Si está vacío y hay producto, va al detalle del producto.', max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo para ocultarlo sin borrarlo.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, help_text="Solo si el tipo es 'Producto del catálogo'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destacados_mes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Producto del mes',
                'verbose_name_plural': 'Productos del mes',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
