# Generated by Django 5.2.15 on 2026-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_productodelmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='productodelmes',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PRODUCTO', 'Producto del catálogo'), ('PERSONALIZADO', 'Contenido personalizado')], default='PRODUCTO', max_length=15),
        ),
    ]
