# Generated by Django 5.2.15 on 2026-07-31 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionramo',
            name='cantidad_girasoles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracionramo',
            name='cantidad_rosas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='configuracionramo',
            name='color_cinta',
        ),
        migrations.AlterField(
            model_name='configuracionramo',
            name='color_rosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.iteminventario'),
        ),
        migrations.AddField(
            model_name='configuracionramo',
            name='color_cinta',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventario.iteminventario'),
        ),
    ]
