# Generated by Django 5.2.15 on 2026-08-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_configuracionramo_cantidad_girasoles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='notas',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='Bogotá', max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_anonima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_regalo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_destinatario',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_destinatario',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('SOACHA', 'Recoger en Soacha'), ('PLAZA', 'Recoger en Plaza de las Américas')], default='DOMICILIO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
