# Generated by Django 5.2.15 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_notas_pedido_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionramo',
            name='pliegos_utilizados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pliegos de papel descontados para este ramo (calculados por tabla o ingresados manualmente en pedidos de 50/100 flores).'),
        ),
        migrations.AddField(
            model_name='configuracionramo',
            name='tipo_armado',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Flores individuales'), ('RAMO', 'En ramo')], help_text='Solo aplica para pedidos de 50 o 100 flores. Dato informativo, no afecta cálculos.', max_length=10, null=True),
        ),
    ]
