# Generated by Django 5.2.15 on 2026-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_iteminventario_stock_actual_and_more'),
        ('pedidos', '0004_configuracionramo_pliegos_utilizados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionramo',
            name='color_rosa',
        ),
        migrations.AddField(
            model_name='configuracionramo',
            name='cantidad_lirios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracionramo',
            name='color_lirio',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventario.iteminventario'),
        ),
    ]
