# Generated by Django 5.2.15 on 2026-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_configuracionramo_color_rosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('SOACHA', 'Recoger en tienda ubicada en Soacha'), ('PLAZA', 'Recoger en Plaza de las Américas'), ('MOSTRADOR', 'Venta presencial en mostrador')], default='DOMICILIO', max_length=20),
        ),
    ]
