# Generated by Django 5.2.15 on 2026-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_comercial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Venta',
                'verbose_name_plural': 'Historial de Ventas',
                'ordering': ['fecha_inicio', 'producto'],
            },
        ),
    ]
